name: pulsar-kafka
version: '3.8'

services:
  # kafka:
  #   container_name: kafka
  #   image: confluentinc/cp-kafka:7.5.2
  #   ports:
  #     - 9092:9092
  #   environment: 
  #     KAFKA_NODE_ID: 1
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT, PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092, PLAINTEXT_HOST://kafka:9092
  #     KAFKA_JMX_PORT: 9101
  #     KAFKA_JMX_HOSTNAME: localhost
  #     KAFKA_PROCESS_ROLES: broker, controller
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
  #     KAFKA_LISTENERS: PLAINTEXT://kafka:29092, CONTROLLER://kafka:29093, PLAINTEXT_HOST://0.0.0.0:9092
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  #   command: |
  #     sh -c "export CLUSTER_ID=$(/bin/kafka-storage random-uuid) &&
  #     exec /etc/confluent/docker/run"
  #   volumes:
  #     - ./server.properties:/etc/kafka/server.properties

  # kafka-ui:
  #   container_name: kafka-ui
  #   image: confluentinc/cp-enterprise-control-center:7.4.3
  #   ports:
  #     - 9021:9021
  #   depends_on:
  #     - kafka
  #   environment:
  #     CONTROL_CENTER_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
  #     CONTROL_CENTER_REPLICATION_FACTOR: 1

  pulsar:
    container_name: pulsar
    build: .
    ports:
      - 6650:6650
      - 8080:8080
    volumes:
      - ./pulsar/data:/pulsar